- hosts: localhost
  tasks:

    # Docker
    - name: "Install Docker"
      apt:
        name: docker.io
      become: true
      tags: docker

    # Sublime Text
    - name: "Install Sublime Text"
      snap:
        name: sublime-text
        classic: true
      become: true
      tags: sublime-text
    - name: "Install Sublime Text dependencies"
      apt:
        name:
          - libgl1
          - libcanberra-gtk-module 
          - libcanberra-gtk3-module
      become: true
      tags: sublime-text

    - name: "Install Gitkraken"
      snap:
        name: gitkraken
        classic: true
      become: true
      tags: gitkraken

    - name: "Install Visual Studio Code"
      snap:
        name: code
        classic: true
      become: true
      tags: visual-studio-code

    - name: "Git clone workspace projects"
      git:
        repo: "git@github.com:cduployez/{{ item }}.git"
        dest: "~/workspace/{{ item }}"
      loop:
        - angular-resume
        - svelte-resume
      tags: git-clone
