---
- name: Create scripts folder
  file:
    path: "{{ workspace_path }}/scripts"
    state: directory

- name: Create scripts/lib folder
  file:
    path: "{{ workspace_path }}/scripts/lib"
    state: directory

- name: Replace variables and copy lib scripts in workspace folder
  template:
    src: "{{ item }}"
    dest: "{{ workspace_path }}/scripts/lib/{{ item | basename | regex_replace('(.j2)$', '') }}"
    mode: u+x
  with_fileglob:
       - templates/lib/*.j2

- name: Replace variables and copy shortcut scripts in workspace folder
  template:
    src: "{{ item }}"
    dest: "{{ workspace_path }}/scripts/{{ item | basename | regex_replace('(.j2)$', '') }}"
    mode: u+x
  with_fileglob:
       - templates/*.j2

- name: Create Windows wsl-utils destination directory
  file:
    path: /mnt/c/wsl-utils
    state: directory

- name: Copy scripts to Windows wsl-utils destination directory
  copy:
    src: files/run-background.vbs
    dest: /mnt/c/wsl-utils/run-background.vbs

- name: Create WSL Icons folder
  file:
    path: /mnt/c/wsl-utils/icons
    state: directory

- name: Install ImageMagick, used to convert SVG to ICO in shortcut scripts
  apt:
    pkg:
      - inkscape
      - imagemagick
  become: true
