---
- name: Create workspace directory
  file:
    path: "{{ workspace_path }}"
    state: directory
    mode: "0755"

- name: Create workspace-data directory
  file:
    path: "{{ workspace_data_path }}"
    state: directory
    mode: "0755"

- name: Git clone projects
  git:
    repo: "git@github.com:cduployez/{{ item }}.git"
    dest: "{{ workspace_path }}/{{ item }}"
  loop: "{{ front_projects + back_projects + util_projects }}"
