---
- name: Add dependencies necessary for Markdown preview to work in Jetbrains IDEs # https://stackoverflow.com/a/78719817/13181578
  apt:
    pkg:
      - libnss3-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
      - libxss-dev
      - libasound2
    state: latest
  become: true
