---
- name: Install dependencies
  apt:
    name: zip, unzip
    state: present
  become: true

- name: Create sdkman directory
  file:
    path: /usr/local/dev
    state: directory
    owner: cduployez
    mode: 0775
  become: true

- name: Download sdkman
  get_url:
    url: https://get.sdkman.io
    dest: /usr/local/dev/sdkman-script.sh
    validate_certs: true

- name: Init sdkman
  shell:
    cmd: "export SDKMAN_DIR=\"/usr/local/dev/sdkman\" && /bin/bash /usr/local/dev/sdkman-script.sh"

# sdk list java | grep -E -o '11.[0-9\.]*-open' | head -n 1
- name: Install Java and Maven
  shell: |
    export SDKMAN_DIR='/usr/local/dev/sdkman' &&
    source /usr/local/dev/sdkman/bin/sdkman-init.sh &&
    JAVA_VERSION=$(sdk list java | grep -E -o '21.[0-9\.]*-tem' | head -n 1) &&
    sdk install java ${JAVA_VERSION}
    sdk install maven
    sdk flush archives
  args:
    executable: /bin/bash

- name: Delete sdkman script
  file:
    path: /bin/bash /usr/local/dev/sdkman-script.sh
    state: absent
