---
- name: Install dependencies
  apt:
    name: zip, unzip
    state: present
  become: true

- name: Create sdkman directory
  file:
    path: /usr/local/dev
    state: directory
    owner: cduployez
    mode: 0775
  become: true

- name: Download sdkman
  get_url:
    url: https://get.sdkman.io
    dest: /usr/local/dev/sdkman-script.sh
    validate_certs: true

- name: Init sdkman
  shell:
    cmd: "export SDKMAN_DIR=\"/usr/local/dev/sdkman\" && /bin/bash /usr/local/dev/sdkman-script.sh"
